create table project.races (raceId int,
year int,
round int,
circuitId int,
name text,
date date,
time text,
url text,
fp1_date text,
fp1_time text,
fp2_date text,
fp2_time text,
fp3_date text,
fp3_time text,
quali_date text,
quali_time text,
sprint_date text,
sprint_time text)